// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for VITURE XR Glasses C SDK and Custom Bridge
class VitureKitBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VitureKitBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VitureKitBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief Non-Android variant: Create an XRDeviceProvider instance
  ///
  /// The non-Android signature accepts only `product_id`
  ///
  /// @param product_id Product ID of the opened usb device
  /// @return Handle to the created instance, or NULL on failure
  XRDeviceProviderHandle xr_device_provider_create(int product_id) {
    return _xr_device_provider_create(product_id);
  }

  late final _xr_device_provider_createPtr =
      _lookup<ffi.NativeFunction<XRDeviceProviderHandle Function(ffi.Int)>>(
        'xr_device_provider_create',
      );
  late final _xr_device_provider_create = _xr_device_provider_createPtr
      .asFunction<XRDeviceProviderHandle Function(int)>();

  /// @brief Initialize the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param custom_config Optional custom configuration string (can be NULL)
  /// @param cache_file_dir Optional directory path for caching data (can be NULL).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle or invalid config
  /// - VITURE_GLASSES_ERROR_CALIB_INIT   calibration initialization failed
  /// - VITURE_GLASSES_ERROR_SERIAL_FETCH serial number retrieval failed
  /// - VITURE_GLASSES_ERROR_UNKNOWN      other error
  int xr_device_provider_initialize(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Char> custom_config,
    ffi.Pointer<ffi.Char> cache_file_dir,
  ) {
    return _xr_device_provider_initialize(
      handle,
      custom_config,
      cache_file_dir,
    );
  }

  late final _xr_device_provider_initializePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('xr_device_provider_initialize');
  late final _xr_device_provider_initialize = _xr_device_provider_initializePtr
      .asFunction<
        int Function(
          XRDeviceProviderHandle,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief Start the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_start(XRDeviceProviderHandle handle) {
    return _xr_device_provider_start(handle);
  }

  late final _xr_device_provider_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_start',
      );
  late final _xr_device_provider_start = _xr_device_provider_startPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Stop the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_stop(XRDeviceProviderHandle handle) {
    return _xr_device_provider_stop(handle);
  }

  late final _xr_device_provider_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_stop',
      );
  late final _xr_device_provider_stop = _xr_device_provider_stopPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Shutdown the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_shutdown(XRDeviceProviderHandle handle) {
    return _xr_device_provider_shutdown(handle);
  }

  late final _xr_device_provider_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_shutdown',
      );
  late final _xr_device_provider_shutdown = _xr_device_provider_shutdownPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Destroy the XRDeviceProvider instance
  /// @param handle Handle to the XRDeviceProvider instance
  void xr_device_provider_destroy(XRDeviceProviderHandle handle) {
    return _xr_device_provider_destroy(handle);
  }

  late final _xr_device_provider_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_destroy',
      );
  late final _xr_device_provider_destroy = _xr_device_provider_destroyPtr
      .asFunction<void Function(XRDeviceProviderHandle)>();

  /// Get core thread IDs, need to be called after start
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param thread_ids Array to store 2 thread IDs for USB data processing
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_thread_id(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Int> thread_ids,
  ) {
    return _xr_device_provider_get_thread_id(handle, thread_ids);
  }

  late final _xr_device_provider_get_thread_idPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Int>)
        >
      >('xr_device_provider_get_thread_id');
  late final _xr_device_provider_get_thread_id =
      _xr_device_provider_get_thread_idPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Int>)
          >();

  /// @brief Register glass state callback
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param callback Called when glass state changes
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or null callback
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_register_state_callback(
    XRDeviceProviderHandle handle,
    GlassStateCallback callback,
  ) {
    return _xr_device_provider_register_state_callback(handle, callback);
  }

  late final _xr_device_provider_register_state_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, GlassStateCallback)
        >
      >('xr_device_provider_register_state_callback');
  late final _xr_device_provider_register_state_callback =
      _xr_device_provider_register_state_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, GlassStateCallback)
          >();

  /// @brief Get the device type
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return XRDeviceType enum value on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_device_type(XRDeviceProviderHandle handle) {
    return _xr_device_provider_get_device_type(handle);
  }

  late final _xr_device_provider_get_device_typePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_get_device_type',
      );
  late final _xr_device_provider_get_device_type =
      _xr_device_provider_get_device_typePtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// Check if product id is valid
  /// @param product_id Product id to check
  /// @return 1 if valid, 0 if not
  int xr_device_provider_is_product_id_valid(int product_id) {
    return _xr_device_provider_is_product_id_valid(product_id);
  }

  late final _xr_device_provider_is_product_id_validPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'xr_device_provider_is_product_id_valid',
      );
  late final _xr_device_provider_is_product_id_valid =
      _xr_device_provider_is_product_id_validPtr
          .asFunction<int Function(int)>();

  /// Check if product support native dof
  /// @param product_id Product id to check
  /// @return 1 if support, 0 if not
  int xr_device_provider_is_product_support_native_dof(int product_id) {
    return _xr_device_provider_is_product_support_native_dof(product_id);
  }

  late final _xr_device_provider_is_product_support_native_dofPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'xr_device_provider_is_product_support_native_dof',
      );
  late final _xr_device_provider_is_product_support_native_dof =
      _xr_device_provider_is_product_support_native_dofPtr
          .asFunction<int Function(int)>();

  /// Check if product supports the given IMU report frequency in the given IMU mode.
  /// Frequency support can differ between raw and pose modes on some products.
  /// VITURE_IMU_FREQUENCY_ULTRA_HIGH (1000Hz) is only available on select products.
  /// @param product_id Product id to check
  /// @param imu_mode IMU mode to check (VITURE_IMU_MODE_RAW / VITURE_IMU_MODE_POSE)
  /// @param imu_report_frequency Frequency to check (VITURE_IMU_FREQUENCY_* constants)
  /// @return 1 if support, 0 if not
  int xr_device_provider_is_product_support_imu_frequency(
    int product_id,
    int imu_mode,
    int imu_report_frequency,
  ) {
    return _xr_device_provider_is_product_support_imu_frequency(
      product_id,
      imu_mode,
      imu_report_frequency,
    );
  }

  late final _xr_device_provider_is_product_support_imu_frequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'xr_device_provider_is_product_support_imu_frequency',
      );
  late final _xr_device_provider_is_product_support_imu_frequency =
      _xr_device_provider_is_product_support_imu_frequencyPtr
          .asFunction<int Function(int, int, int)>();

  /// Get glasses market name
  /// @param product_id Viture product id
  /// @param market_name Buffer to store market name
  /// @param length Pointer to store the length of market name
  int xr_device_provider_get_market_name(
    int product_id,
    ffi.Pointer<ffi.Char> market_name,
    ffi.Pointer<ffi.Int> length,
  ) {
    return _xr_device_provider_get_market_name(product_id, market_name, length);
  }

  late final _xr_device_provider_get_market_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
        >
      >('xr_device_provider_get_market_name');
  late final _xr_device_provider_get_market_name =
      _xr_device_provider_get_market_namePtr
          .asFunction<
            int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
          >();

  /// Set log level
  /// @param level 0: No log, 1: Error, 2: Info, 3: Debug
  void xr_device_provider_set_log_level(int level) {
    return _xr_device_provider_set_log_level(level);
  }

  late final _xr_device_provider_set_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'xr_device_provider_set_log_level',
      );
  late final _xr_device_provider_set_log_level =
      _xr_device_provider_set_log_levelPtr.asFunction<void Function(int)>();

  /// Get log level
  /// @return 0: No log, 1: Error, 2: Info, 3: Debug
  int xr_device_provider_get_log_level() {
    return _xr_device_provider_get_log_level();
  }

  late final _xr_device_provider_get_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'xr_device_provider_get_log_level',
      );
  late final _xr_device_provider_get_log_level =
      _xr_device_provider_get_log_levelPtr.asFunction<int Function()>();

  /// Set a log hook to capture library log messages
  ///
  /// When a log hook is set, all log messages will be passed to the callback
  /// in addition to the default logging mechanism (Android log or stdio).
  /// This allows applications to redirect logs to custom handlers such as:
  /// - Remote logging services
  /// - Log files
  /// - Crash reporting systems
  /// - Custom logging frameworks
  ///
  /// @param hook Callback function to handle log messages. Pass NULL to disable the hook.
  ///
  /// Example usage:
  /// @code
  /// void my_log_hook(int level, const char* tag, const char* message) {
  /// // Send to custom logger or file
  /// my_logger_write(level, tag, message);
  /// }
  ///
  /// xr_device_provider_set_log_hook(my_log_hook);
  /// @endcode
  void xr_device_provider_set_log_hook(LogHook hook) {
    return _xr_device_provider_set_log_hook(hook);
  }

  late final _xr_device_provider_set_log_hookPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LogHook)>>(
        'xr_device_provider_set_log_hook',
      );
  late final _xr_device_provider_set_log_hook =
      _xr_device_provider_set_log_hookPtr.asFunction<void Function(LogHook)>();

  /// @brief Register imu raw data callback.
  ///
  /// This function associates a user-provided callback with the device
  /// identified by `handle`. The callback will be invoked from the internal
  /// imu read thread when imu raw data is available.
  ///
  /// @param handle           Handle to the `XRDeviceProvider` instance.
  /// @param imu_raw_callback Callback function pointer.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_imu_raw_callback(
    XRDeviceProviderHandle handle,
    VitureImuRawCallback imu_raw_callback,
  ) {
    return _xr_device_provider_register_imu_raw_callback(
      handle,
      imu_raw_callback,
    );
  }

  late final _xr_device_provider_register_imu_raw_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, VitureImuRawCallback)
        >
      >('xr_device_provider_register_imu_raw_callback');
  late final _xr_device_provider_register_imu_raw_callback =
      _xr_device_provider_register_imu_raw_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, VitureImuRawCallback)
          >();

  /// @brief Register a combined IMU + VSync callback for a Viture device.
  ///
  /// This function associates a user-provided callback with the device
  /// identified by `handle`. The callback will be invoked from the internal
  /// imu read thread when imu pose data is available.
  ///
  /// @param handle            Handle to the `XRDeviceProvider` instance.
  /// @param imu_pose_callback Callback function pointer.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_imu_pose_callback(
    XRDeviceProviderHandle handle,
    VitureImuPoseCallback imu_pose_callback,
  ) {
    return _xr_device_provider_register_imu_pose_callback(
      handle,
      imu_pose_callback,
    );
  }

  late final _xr_device_provider_register_imu_pose_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, VitureImuPoseCallback)
        >
      >('xr_device_provider_register_imu_pose_callback');
  late final _xr_device_provider_register_imu_pose_callback =
      _xr_device_provider_register_imu_pose_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, VitureImuPoseCallback)
          >();

  /// @brief Open imu (no effect for carina device)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param imu_mode viture::protocol::imu::Mode
  /// @param imu_report_frequency viture::protocol::imu::Frequency. Not all products support all
  /// frequencies; check with xr_device_provider_is_product_support_imu_frequency.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle or frequency out of range
  /// - VITURE_GLASSES_ERROR_USB_EXEC      USB execution error
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED device type or frequency not supported
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_open_imu(
    XRDeviceProviderHandle handle,
    int imu_mode,
    int imu_report_frequency,
  ) {
    return _xr_device_provider_open_imu(handle, imu_mode, imu_report_frequency);
  }

  late final _xr_device_provider_open_imuPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Uint8, ffi.Uint8)
        >
      >('xr_device_provider_open_imu');
  late final _xr_device_provider_open_imu = _xr_device_provider_open_imuPtr
      .asFunction<int Function(XRDeviceProviderHandle, int, int)>();

  /// @brief Close IMU (no effect for Carina device)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param imu_mode viture::protocol::imu::Mode
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_USB_EXEC      USB execution error
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED device type not supported
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_close_imu(
    XRDeviceProviderHandle handle,
    int imu_mode,
  ) {
    return _xr_device_provider_close_imu(handle, imu_mode);
  }

  late final _xr_device_provider_close_imuPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle, ffi.Uint8)>
      >('xr_device_provider_close_imu');
  late final _xr_device_provider_close_imu = _xr_device_provider_close_imuPtr
      .asFunction<int Function(XRDeviceProviderHandle, int)>();

  /// @brief Register callbacks for a Carina device instance.
  ///
  /// Callbacks registered here are ignored for devices that are not
  /// `XR_DEVICE_TYPE_VITURE_CARINA`.
  ///
  /// @param handle         Opaque device provider handle.
  /// @param pose_callback  Callback for pose samples.
  /// @param vsync_callback Callback for VSync events.
  /// @param imu_callback   Callback for IMU samples.
  /// @param camera_callback Callback for stereo camera frames.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_callbacks_carina(
    XRDeviceProviderHandle handle,
    XRPoseCallback pose_callback,
    XRVSyncCallback vsync_callback,
    XRImuCallback imu_callback,
    XRCameraCallback camera_callback,
  ) {
    return _xr_device_provider_register_callbacks_carina(
      handle,
      pose_callback,
      vsync_callback,
      imu_callback,
      camera_callback,
    );
  }

  late final _xr_device_provider_register_callbacks_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            XRPoseCallback,
            XRVSyncCallback,
            XRImuCallback,
            XRCameraCallback,
          )
        >
      >('xr_device_provider_register_callbacks_carina');
  late final _xr_device_provider_register_callbacks_carina =
      _xr_device_provider_register_callbacks_carinaPtr
          .asFunction<
            int Function(
              XRDeviceProviderHandle,
              XRPoseCallback,
              XRVSyncCallback,
              XRImuCallback,
              XRCameraCallback,
            )
          >();

  /// @brief Set DOF type for Carina device. Must be called after xr_device_provider_create
  /// and before xr_device_provider_initialize. Default is 6DOF.
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param is_6dof 1 for 6DOF, 0 for 3DOF
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_dof_type_carina(
    XRDeviceProviderHandle handle,
    int is_6dof,
  ) {
    return _xr_device_provider_set_dof_type_carina(handle, is_6dof);
  }

  late final _xr_device_provider_set_dof_type_carinaPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle, ffi.Int)>
      >('xr_device_provider_set_dof_type_carina');
  late final _xr_device_provider_set_dof_type_carina =
      _xr_device_provider_set_dof_type_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle, int)>();

  /// @brief Trigger a full VIO re-initialisation.
  ///
  /// Resets the Carina tracking state, including position and yaw.  Pitch and roll remain
  /// gravity-anchored and are not affected.
  ///
  /// This is a heavyweight operation that briefly interrupts tracking.  Prefer
  /// xr_device_provider_reset_origin_carina() for lightweight heading/position recentering.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_reset_pose_carina(XRDeviceProviderHandle handle) {
    return _xr_device_provider_reset_pose_carina(handle);
  }

  late final _xr_device_provider_reset_pose_carinaPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_reset_pose_carina',
      );
  late final _xr_device_provider_reset_pose_carina =
      _xr_device_provider_reset_pose_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Set a new tracking origin in OpenGL coordinate system (x -> right, y -> up, z -> backward).
  ///
  /// After this call, subsequent xr_device_provider_get_gl_pose_carina() returns poses expressed
  /// relative to the specified origin.
  ///
  /// Typical uses:
  /// - Pass the pose returned by xr_device_provider_get_gl_pose_carina() to reset position and
  /// yaw to the user's current physical state.
  /// - Pass a manually constructed pose to relocate the tracking origin to any desired position
  /// and heading (e.g. teleporting the camera to a fixed point in the scene).
  ///
  /// Axis reset behaviour:
  /// - Position is reset to the translation encoded in `pose`.
  /// - Yaw is reset to the yaw component of the quaternion in `pose`.
  /// - Pitch and roll are gravity-anchored by the Carina VIO system and are NOT affected by this
  /// call regardless of the quaternion passed.  They always reflect the device's absolute
  /// orientation relative to gravity.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param pose   Target origin pose: [px, py, pz, qw, qx, qy, qz].
  /// Pass the result of xr_device_provider_get_gl_pose_carina() to anchor the origin
  /// at the current physical pose, or supply a custom pose to teleport to a specific
  /// location and heading.
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_reset_origin_carina(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Float> pose,
  ) {
    return _xr_device_provider_reset_origin_carina(handle, pose);
  }

  late final _xr_device_provider_reset_origin_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Float>)
        >
      >('xr_device_provider_reset_origin_carina');
  late final _xr_device_provider_reset_origin_carina =
      _xr_device_provider_reset_origin_carinaPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Float>)
          >();

  /// @brief Get IMU pose data with prediction time (Twb matrix in OpenGL coordinate system: x -> right, y -> up, z -> backward)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param pose Array to store pose data (7 floats for position and quaternion)
  /// @param predict_time Prediction time in seconds, 0 for current pose data
  /// @param pose_status Output pose status: 0 = stable, 1 = unstable (may occur briefly after device start). Can be null.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_gl_pose_carina(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Float> pose,
    double predict_time,
    ffi.Pointer<ffi.Int> pose_status,
  ) {
    return _xr_device_provider_get_gl_pose_carina(
      handle,
      pose,
      predict_time,
      pose_status,
    );
  }

  late final _xr_device_provider_get_gl_pose_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            ffi.Pointer<ffi.Float>,
            ffi.Double,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('xr_device_provider_get_gl_pose_carina');
  late final _xr_device_provider_get_gl_pose_carina =
      _xr_device_provider_get_gl_pose_carinaPtr
          .asFunction<
            int Function(
              XRDeviceProviderHandle,
              ffi.Pointer<ffi.Float>,
              double,
              ffi.Pointer<ffi.Int>,
            )
          >();

  /// @brief Enable automatic exposure for the Carina camera.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_auto_exposure_carina(
    XRDeviceProviderHandle handle,
  ) {
    return _xr_device_provider_set_auto_exposure_carina(handle);
  }

  late final _xr_device_provider_set_auto_exposure_carinaPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_set_auto_exposure_carina',
      );
  late final _xr_device_provider_set_auto_exposure_carina =
      _xr_device_provider_set_auto_exposure_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Set manual (fixed) exposure for the Carina camera.
  ///
  /// Disables automatic exposure and applies the given exposure time and gain.
  /// Out-of-range values are clamped to the accepted ranges.
  ///
  /// @param handle           Handle to the XRDeviceProvider instance
  /// @param exposure_time_ms Exposure time in milliseconds, range [0.01, 8.0].
  /// @param exposure_gain    Sensor gain, range [0, 15].
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_manual_exposure_carina(
    XRDeviceProviderHandle handle,
    double exposure_time_ms,
    int exposure_gain,
  ) {
    return _xr_device_provider_set_manual_exposure_carina(
      handle,
      exposure_time_ms,
      exposure_gain,
    );
  }

  late final _xr_device_provider_set_manual_exposure_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Float, ffi.Int)
        >
      >('xr_device_provider_set_manual_exposure_carina');
  late final _xr_device_provider_set_manual_exposure_carina =
      _xr_device_provider_set_manual_exposure_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle, double, int)>();
}

/// @brief Handle type for XRDeviceProvider instances. This is an opaque pointer
/// returned by `xr_device_provider_create` and consumed by other API calls.
typedef XRDeviceProviderHandle = ffi.Pointer<ffi.Void>;
typedef GlassStateCallbackFunction = ffi.Void Function(
  ffi.Int glass_state_id,
  ffi.Int glass_value,
);
typedef DartGlassStateCallbackFunction = void Function(
  int glass_state_id,
  int glass_value,
);

/// @brief Callback for reporting glass state changes (brightness, volume, display mode, etc.)
///
/// See `VITURE_CALLBACK_ID_*` constants in viture_protocol_public.h for detailed id and values
///
/// @param glass_state_id  Identifier for the state being reported.
/// @param glass_value     Integer value associated with the state.
typedef GlassStateCallback =
    ffi.Pointer<ffi.NativeFunction<GlassStateCallbackFunction>>;
typedef LogHookFunction = ffi.Void Function(
  ffi.Int level,
  ffi.Pointer<ffi.Char> tag,
  ffi.Pointer<ffi.Char> message,
);
typedef DartLogHookFunction = void Function(
  int level,
  ffi.Pointer<ffi.Char> tag,
  ffi.Pointer<ffi.Char> message,
);

/// @brief Log hook function type
///
/// This callback is invoked for each log message generated by the library.
/// It allows external applications to capture, filter, or redirect log messages
/// to custom logging systems (files, remote servers, crash reporting, etc.).
///
/// @param level Log level (0: None, 1: Error, 2: Info, 3: Debug)
/// @param tag Log tag (typically "libglasses")
/// @param message Log message content
typedef LogHook = ffi.Pointer<ffi.NativeFunction<LogHookFunction>>;
typedef VitureImuRawCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> data,
  ffi.Uint64 timestamp,
  ffi.Uint64 vsync,
);
typedef DartVitureImuRawCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> data,
  int timestamp,
  int vsync,
);

/// @brief Callback function type for imu raw data.
///
/// @param data      Pointer to raw data buffer (device-defined layout).
/// @param timestamp Timestamp in device timebase for IMU sample.
/// @param vsync     VSync timestamp associated with the sample.
///
/// Should be set before calling xr_device_provider_open_imu with VITURE_IMU_MODE_RAW
/// Data format:
/// 1. Viture One / Pro / Lite: [gyroscope_raw_x, gyroscope_raw_y, gyroscope_raw_z,
/// accelerometer_raw_x, accelerometer_raw_y, accelerometer_raw_z,
/// 0, 0, 0,
/// temperature]
/// 2. Viture Luma / Luma Pro / Beast / Pro 2: [gyroscope_raw_x, gyroscope_raw_y, gyroscope_raw_z,
/// accelerometer_raw_x, accelerometer_raw_y, accelerometer_raw_z,
/// magnetometer_raw_x, magnetometer_raw_y, magnetometer_raw_z,
/// temperature]
typedef VitureImuRawCallback =
    ffi.Pointer<ffi.NativeFunction<VitureImuRawCallbackFunction>>;
typedef VitureImuPoseCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> data,
  ffi.Uint64 timestamp,
);
typedef DartVitureImuPoseCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> data,
  int timestamp,
);

/// @brief Callback function type for imu pose data.
///
/// @param data      Pointer to pose data buffer
/// @param timestamp Timestamp in device timebase for IMU sample.
///
/// Should be set before calling xr_device_provider_open_imu with VITURE_IMU_MODE_POSE
/// Coordinate system: North-West-Up (NWU), X->North, Y->West, Z->Up.
/// Data format: [roll, pitch, yaw, quaternion_w, quaternion_x, quaternion_y, quaternion_z]
typedef VitureImuPoseCallback =
    ffi.Pointer<ffi.NativeFunction<VitureImuPoseCallbackFunction>>;
typedef XRPoseCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> pose,
  ffi.Double timestamp,
);
typedef DartXRPoseCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> pose,
  double timestamp,
);

/// @brief Callback invoked when a new pose sample is available, This function
/// returns pose data at the Camera's frequency (25 Hz). In most cases, this
/// interface can be ignored.
///
/// @param pose      Array of 7 floats: [px, py, pz, qw, qx, qy, qz].
/// @param timestamp Monotonic timestamp in seconds.
typedef XRPoseCallback =
    ffi.Pointer<ffi.NativeFunction<XRPoseCallbackFunction>>;
typedef XRVSyncCallbackFunction = ffi.Void Function(ffi.Double timestamp);
typedef DartXRVSyncCallbackFunction = void Function(double timestamp);

/// @brief VSync notification callback.
///
/// @param timestamp Monotonic timestamp in seconds when VSync occurred.
typedef XRVSyncCallback =
    ffi.Pointer<ffi.NativeFunction<XRVSyncCallbackFunction>>;
typedef XRImuCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> imu,
  ffi.Double timestamp,
);
typedef DartXRImuCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> imu,
  double timestamp,
);

/// @brief IMU data callback for Carina device.
///
/// @param imu       IMU data: [ax, ay, az, gx, gy, gz].
/// @param timestamp Timestamp in seconds for the IMU sample.
typedef XRImuCallback = ffi.Pointer<ffi.NativeFunction<XRImuCallbackFunction>>;
typedef XRCameraCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Char> image_left0,
  ffi.Pointer<ffi.Char> image_right0,
  ffi.Pointer<ffi.Char> image_left1,
  ffi.Pointer<ffi.Char> image_right1,
  ffi.Double timestamp,
  ffi.Int width,
  ffi.Int height,
);
typedef DartXRCameraCallbackFunction = void Function(
  ffi.Pointer<ffi.Char> image_left0,
  ffi.Pointer<ffi.Char> image_right0,
  ffi.Pointer<ffi.Char> image_left1,
  ffi.Pointer<ffi.Char> image_right1,
  double timestamp,
  int width,
  int height,
);

/// @brief Camera frame callback for stereo frames.
///
/// @param image_left0   Pointer to left image buffer (frame 0).
/// @param image_right0  Pointer to right image buffer (frame 0).
/// @param image_left1   Pointer to left image buffer (frame 1).
/// @param image_right1  Pointer to right image buffer (frame 1).
/// @param timestamp     Frame timestamp.
/// @param width         Frame width in pixels.
/// @param height        Frame height in pixels.
typedef XRCameraCallback =
    ffi.Pointer<ffi.NativeFunction<XRCameraCallbackFunction>>;

const int VITURE_GLASSES_SUCCESS = 0;

const int VITURE_GLASSES_ERROR_INVALID_PARAM = -1;

const int VITURE_GLASSES_ERROR_USB_UNAVAILABLE = -2;

const int VITURE_GLASSES_ERROR_USB_EXEC = -3;

const int VITURE_GLASSES_ERROR_NOT_SUPPORTED = -4;

const int VITURE_GLASSES_ERROR_NO_DATA = -5;

const int VITURE_GLASSES_ERROR_DATA_PARSE = -6;

const int VITURE_GLASSES_ERROR_DEVICE_REJECTED = -7;

const int VITURE_GLASSES_ERROR_CALIB_INIT = -8;

const int VITURE_GLASSES_ERROR_SERIAL_FETCH = -9;

const int VITURE_GLASSES_ERROR_INVALID_STATE = -10;

const int VITURE_GLASSES_ERROR_UNKNOWN = -99;

const int LOG_LEVEL_NONE = 0;

const int LOG_LEVEL_ERROR = 1;

const int LOG_LEVEL_INFO = 2;

const int LOG_LEVEL_DEBUG = 3;

const int VITURE_VERSION_MAJOR = 2;

const int VITURE_VERSION_MINOR = 4;

const int VITURE_VERSION_PATCH = 0;

const String VITURE_VERSION_STRING = '2.4.0';
