// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for VITURE XR Glasses C SDK and Custom Bridge
class VitureKitBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VitureKitBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VitureKitBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief Non-Android variant: Create an XRDeviceProvider instance
  ///
  /// The non-Android signature accepts only `product_id`
  ///
  /// @param product_id Product ID of the opened usb device
  /// @return Handle to the created instance, or NULL on failure
  XRDeviceProviderHandle xr_device_provider_create(int product_id) {
    return _xr_device_provider_create(product_id);
  }

  late final _xr_device_provider_createPtr =
      _lookup<ffi.NativeFunction<XRDeviceProviderHandle Function(ffi.Int)>>(
        'xr_device_provider_create',
      );
  late final _xr_device_provider_create = _xr_device_provider_createPtr
      .asFunction<XRDeviceProviderHandle Function(int)>();

  /// @brief Initialize the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param custom_config Optional custom configuration string (can be NULL)
  /// @param cache_file_dir Optional directory path for caching data (can be NULL).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle or invalid config
  /// - VITURE_GLASSES_ERROR_CALIB_INIT   calibration initialization failed
  /// - VITURE_GLASSES_ERROR_SERIAL_FETCH serial number retrieval failed
  /// - VITURE_GLASSES_ERROR_UNKNOWN      other error
  int xr_device_provider_initialize(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Char> custom_config,
    ffi.Pointer<ffi.Char> cache_file_dir,
  ) {
    return _xr_device_provider_initialize(
      handle,
      custom_config,
      cache_file_dir,
    );
  }

  late final _xr_device_provider_initializePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('xr_device_provider_initialize');
  late final _xr_device_provider_initialize = _xr_device_provider_initializePtr
      .asFunction<
        int Function(
          XRDeviceProviderHandle,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// @brief Start the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_start(XRDeviceProviderHandle handle) {
    return _xr_device_provider_start(handle);
  }

  late final _xr_device_provider_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_start',
      );
  late final _xr_device_provider_start = _xr_device_provider_startPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Stop the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_stop(XRDeviceProviderHandle handle) {
    return _xr_device_provider_stop(handle);
  }

  late final _xr_device_provider_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_stop',
      );
  late final _xr_device_provider_stop = _xr_device_provider_stopPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Shutdown the XRDeviceProvider
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_shutdown(XRDeviceProviderHandle handle) {
    return _xr_device_provider_shutdown(handle);
  }

  late final _xr_device_provider_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_shutdown',
      );
  late final _xr_device_provider_shutdown = _xr_device_provider_shutdownPtr
      .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Destroy the XRDeviceProvider instance
  /// @param handle Handle to the XRDeviceProvider instance
  void xr_device_provider_destroy(XRDeviceProviderHandle handle) {
    return _xr_device_provider_destroy(handle);
  }

  late final _xr_device_provider_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_destroy',
      );
  late final _xr_device_provider_destroy = _xr_device_provider_destroyPtr
      .asFunction<void Function(XRDeviceProviderHandle)>();

  /// Get core thread IDs, need to be called after start
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param thread_ids Array to store 2 thread IDs for USB data processing
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_thread_id(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Int> thread_ids,
  ) {
    return _xr_device_provider_get_thread_id(handle, thread_ids);
  }

  late final _xr_device_provider_get_thread_idPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Int>)
        >
      >('xr_device_provider_get_thread_id');
  late final _xr_device_provider_get_thread_id =
      _xr_device_provider_get_thread_idPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Int>)
          >();

  /// @brief Register glass state callback
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param callback Called when glass state changes
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or null callback
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_register_state_callback(
    XRDeviceProviderHandle handle,
    GlassStateCallback callback,
  ) {
    return _xr_device_provider_register_state_callback(handle, callback);
  }

  late final _xr_device_provider_register_state_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, GlassStateCallback)
        >
      >('xr_device_provider_register_state_callback');
  late final _xr_device_provider_register_state_callback =
      _xr_device_provider_register_state_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, GlassStateCallback)
          >();

  /// @brief Get the device type
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return XRDeviceType enum value on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_device_type(XRDeviceProviderHandle handle) {
    return _xr_device_provider_get_device_type(handle);
  }

  late final _xr_device_provider_get_device_typePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_get_device_type',
      );
  late final _xr_device_provider_get_device_type =
      _xr_device_provider_get_device_typePtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// Check if product id is valid
  /// @param product_id Product id to check
  /// @return 1 if valid, 0 if not
  int xr_device_provider_is_product_id_valid(int product_id) {
    return _xr_device_provider_is_product_id_valid(product_id);
  }

  late final _xr_device_provider_is_product_id_validPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'xr_device_provider_is_product_id_valid',
      );
  late final _xr_device_provider_is_product_id_valid =
      _xr_device_provider_is_product_id_validPtr
          .asFunction<int Function(int)>();

  /// Check if product support native dof
  /// @param product_id Product id to check
  /// @return 1 if support, 0 if not
  int xr_device_provider_is_product_support_native_dof(int product_id) {
    return _xr_device_provider_is_product_support_native_dof(product_id);
  }

  late final _xr_device_provider_is_product_support_native_dofPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'xr_device_provider_is_product_support_native_dof',
      );
  late final _xr_device_provider_is_product_support_native_dof =
      _xr_device_provider_is_product_support_native_dofPtr
          .asFunction<int Function(int)>();

  /// Check if product supports the given IMU report frequency in the given IMU mode.
  /// Frequency support can differ between raw and pose modes on some products.
  /// VITURE_IMU_FREQUENCY_ULTRA_HIGH (1000Hz) is only available on select products.
  /// @param product_id Product id to check
  /// @param imu_mode IMU mode to check (VITURE_IMU_MODE_RAW / VITURE_IMU_MODE_POSE)
  /// @param imu_report_frequency Frequency to check (VITURE_IMU_FREQUENCY_* constants)
  /// @return 1 if support, 0 if not
  int xr_device_provider_is_product_support_imu_frequency(
    int product_id,
    int imu_mode,
    int imu_report_frequency,
  ) {
    return _xr_device_provider_is_product_support_imu_frequency(
      product_id,
      imu_mode,
      imu_report_frequency,
    );
  }

  late final _xr_device_provider_is_product_support_imu_frequencyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'xr_device_provider_is_product_support_imu_frequency',
      );
  late final _xr_device_provider_is_product_support_imu_frequency =
      _xr_device_provider_is_product_support_imu_frequencyPtr
          .asFunction<int Function(int, int, int)>();

  /// Get glasses market name
  /// @param product_id Viture product id
  /// @param market_name Buffer to store market name
  /// @param length Pointer to store the length of market name
  int xr_device_provider_get_market_name(
    int product_id,
    ffi.Pointer<ffi.Char> market_name,
    ffi.Pointer<ffi.Int> length,
  ) {
    return _xr_device_provider_get_market_name(product_id, market_name, length);
  }

  late final _xr_device_provider_get_market_namePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
        >
      >('xr_device_provider_get_market_name');
  late final _xr_device_provider_get_market_name =
      _xr_device_provider_get_market_namePtr
          .asFunction<
            int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)
          >();

  /// Set log level
  /// @param level 0: No log, 1: Error, 2: Info, 3: Debug
  void xr_device_provider_set_log_level(int level) {
    return _xr_device_provider_set_log_level(level);
  }

  late final _xr_device_provider_set_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'xr_device_provider_set_log_level',
      );
  late final _xr_device_provider_set_log_level =
      _xr_device_provider_set_log_levelPtr.asFunction<void Function(int)>();

  /// Get log level
  /// @return 0: No log, 1: Error, 2: Info, 3: Debug
  int xr_device_provider_get_log_level() {
    return _xr_device_provider_get_log_level();
  }

  late final _xr_device_provider_get_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'xr_device_provider_get_log_level',
      );
  late final _xr_device_provider_get_log_level =
      _xr_device_provider_get_log_levelPtr.asFunction<int Function()>();

  /// Set a log hook to capture library log messages
  ///
  /// When a log hook is set, all log messages will be passed to the callback
  /// in addition to the default logging mechanism (Android log or stdio).
  /// This allows applications to redirect logs to custom handlers such as:
  /// - Remote logging services
  /// - Log files
  /// - Crash reporting systems
  /// - Custom logging frameworks
  ///
  /// @param hook Callback function to handle log messages. Pass NULL to disable the hook.
  ///
  /// Example usage:
  /// @code
  /// void my_log_hook(int level, const char* tag, const char* message) {
  /// // Send to custom logger or file
  /// my_logger_write(level, tag, message);
  /// }
  ///
  /// xr_device_provider_set_log_hook(my_log_hook);
  /// @endcode
  void xr_device_provider_set_log_hook(LogHook hook) {
    return _xr_device_provider_set_log_hook(hook);
  }

  late final _xr_device_provider_set_log_hookPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LogHook)>>(
        'xr_device_provider_set_log_hook',
      );
  late final _xr_device_provider_set_log_hook =
      _xr_device_provider_set_log_hookPtr.asFunction<void Function(LogHook)>();

  /// @brief Register imu raw data callback.
  ///
  /// This function associates a user-provided callback with the device
  /// identified by `handle`. The callback will be invoked from the internal
  /// imu read thread when imu raw data is available.
  ///
  /// @param handle           Handle to the `XRDeviceProvider` instance.
  /// @param imu_raw_callback Callback function pointer.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_imu_raw_callback(
    XRDeviceProviderHandle handle,
    VitureImuRawCallback imu_raw_callback,
  ) {
    return _xr_device_provider_register_imu_raw_callback(
      handle,
      imu_raw_callback,
    );
  }

  late final _xr_device_provider_register_imu_raw_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, VitureImuRawCallback)
        >
      >('xr_device_provider_register_imu_raw_callback');
  late final _xr_device_provider_register_imu_raw_callback =
      _xr_device_provider_register_imu_raw_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, VitureImuRawCallback)
          >();

  /// @brief Register a combined IMU + VSync callback for a Viture device.
  ///
  /// This function associates a user-provided callback with the device
  /// identified by `handle`. The callback will be invoked from the internal
  /// imu read thread when imu pose data is available.
  ///
  /// @param handle            Handle to the `XRDeviceProvider` instance.
  /// @param imu_pose_callback Callback function pointer.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_imu_pose_callback(
    XRDeviceProviderHandle handle,
    VitureImuPoseCallback imu_pose_callback,
  ) {
    return _xr_device_provider_register_imu_pose_callback(
      handle,
      imu_pose_callback,
    );
  }

  late final _xr_device_provider_register_imu_pose_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, VitureImuPoseCallback)
        >
      >('xr_device_provider_register_imu_pose_callback');
  late final _xr_device_provider_register_imu_pose_callback =
      _xr_device_provider_register_imu_pose_callbackPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, VitureImuPoseCallback)
          >();

  /// @brief Open imu (no effect for carina device)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param imu_mode viture::protocol::imu::Mode
  /// @param imu_report_frequency viture::protocol::imu::Frequency. Not all products support all
  /// frequencies; check with xr_device_provider_is_product_support_imu_frequency.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle or frequency out of range
  /// - VITURE_GLASSES_ERROR_USB_EXEC      USB execution error
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED device type or frequency not supported
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_open_imu(
    XRDeviceProviderHandle handle,
    int imu_mode,
    int imu_report_frequency,
  ) {
    return _xr_device_provider_open_imu(handle, imu_mode, imu_report_frequency);
  }

  late final _xr_device_provider_open_imuPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Uint8, ffi.Uint8)
        >
      >('xr_device_provider_open_imu');
  late final _xr_device_provider_open_imu = _xr_device_provider_open_imuPtr
      .asFunction<int Function(XRDeviceProviderHandle, int, int)>();

  /// @brief Close IMU (no effect for Carina device)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param imu_mode viture::protocol::imu::Mode
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM null handle
  /// - VITURE_GLASSES_ERROR_USB_EXEC      USB execution error
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED device type not supported
  /// - VITURE_GLASSES_ERROR_UNKNOWN       other error
  int xr_device_provider_close_imu(
    XRDeviceProviderHandle handle,
    int imu_mode,
  ) {
    return _xr_device_provider_close_imu(handle, imu_mode);
  }

  late final _xr_device_provider_close_imuPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle, ffi.Uint8)>
      >('xr_device_provider_close_imu');
  late final _xr_device_provider_close_imu = _xr_device_provider_close_imuPtr
      .asFunction<int Function(XRDeviceProviderHandle, int)>();

  /// @brief Register callbacks for a Carina device instance.
  ///
  /// Callbacks registered here are ignored for devices that are not
  /// `XR_DEVICE_TYPE_VITURE_CARINA`.
  ///
  /// @param handle         Opaque device provider handle.
  /// @param pose_callback  Callback for pose samples.
  /// @param vsync_callback Callback for VSync events.
  /// @param imu_callback   Callback for IMU samples.
  /// @param camera_callback Callback for stereo camera frames.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure.
  int xr_device_provider_register_callbacks_carina(
    XRDeviceProviderHandle handle,
    XRPoseCallback pose_callback,
    XRVSyncCallback vsync_callback,
    XRImuCallback imu_callback,
    XRCameraCallback camera_callback,
  ) {
    return _xr_device_provider_register_callbacks_carina(
      handle,
      pose_callback,
      vsync_callback,
      imu_callback,
      camera_callback,
    );
  }

  late final _xr_device_provider_register_callbacks_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            XRPoseCallback,
            XRVSyncCallback,
            XRImuCallback,
            XRCameraCallback,
          )
        >
      >('xr_device_provider_register_callbacks_carina');
  late final _xr_device_provider_register_callbacks_carina =
      _xr_device_provider_register_callbacks_carinaPtr
          .asFunction<
            int Function(
              XRDeviceProviderHandle,
              XRPoseCallback,
              XRVSyncCallback,
              XRImuCallback,
              XRCameraCallback,
            )
          >();

  /// @brief Set DOF type for Carina device. Must be called after xr_device_provider_create
  /// and before xr_device_provider_initialize. Default is 6DOF.
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param is_6dof 1 for 6DOF, 0 for 3DOF
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_dof_type_carina(
    XRDeviceProviderHandle handle,
    int is_6dof,
  ) {
    return _xr_device_provider_set_dof_type_carina(handle, is_6dof);
  }

  late final _xr_device_provider_set_dof_type_carinaPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle, ffi.Int)>
      >('xr_device_provider_set_dof_type_carina');
  late final _xr_device_provider_set_dof_type_carina =
      _xr_device_provider_set_dof_type_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle, int)>();

  /// @brief Trigger a full VIO re-initialisation.
  ///
  /// Resets the Carina tracking state, including position and yaw.  Pitch and roll remain
  /// gravity-anchored and are not affected.
  ///
  /// This is a heavyweight operation that briefly interrupts tracking.  Prefer
  /// xr_device_provider_reset_origin_carina() for lightweight heading/position recentering.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_reset_pose_carina(XRDeviceProviderHandle handle) {
    return _xr_device_provider_reset_pose_carina(handle);
  }

  late final _xr_device_provider_reset_pose_carinaPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_reset_pose_carina',
      );
  late final _xr_device_provider_reset_pose_carina =
      _xr_device_provider_reset_pose_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Set a new tracking origin in OpenGL coordinate system (x -> right, y -> up, z -> backward).
  ///
  /// After this call, subsequent xr_device_provider_get_gl_pose_carina() returns poses expressed
  /// relative to the specified origin.
  ///
  /// Typical uses:
  /// - Pass the pose returned by xr_device_provider_get_gl_pose_carina() to reset position and
  /// yaw to the user's current physical state.
  /// - Pass a manually constructed pose to relocate the tracking origin to any desired position
  /// and heading (e.g. teleporting the camera to a fixed point in the scene).
  ///
  /// Axis reset behaviour:
  /// - Position is reset to the translation encoded in `pose`.
  /// - Yaw is reset to the yaw component of the quaternion in `pose`.
  /// - Pitch and roll are gravity-anchored by the Carina VIO system and are NOT affected by this
  /// call regardless of the quaternion passed.  They always reflect the device's absolute
  /// orientation relative to gravity.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param pose   Target origin pose: [px, py, pz, qw, qx, qy, qz].
  /// Pass the result of xr_device_provider_get_gl_pose_carina() to anchor the origin
  /// at the current physical pose, or supply a custom pose to teleport to a specific
  /// location and heading.
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_reset_origin_carina(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Float> pose,
  ) {
    return _xr_device_provider_reset_origin_carina(handle, pose);
  }

  late final _xr_device_provider_reset_origin_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Float>)
        >
      >('xr_device_provider_reset_origin_carina');
  late final _xr_device_provider_reset_origin_carina =
      _xr_device_provider_reset_origin_carinaPtr
          .asFunction<
            int Function(XRDeviceProviderHandle, ffi.Pointer<ffi.Float>)
          >();

  /// @brief Get IMU pose data with prediction time (Twb matrix in OpenGL coordinate system: x -> right, y -> up, z -> backward)
  /// @param handle Handle to the XRDeviceProvider instance
  /// @param pose Array to store pose data (7 floats for position and quaternion)
  /// @param predict_time Prediction time in seconds, 0 for current pose data
  /// @param pose_status Output pose status: 0 = stable, 1 = unstable (may occur briefly after device start). Can be null.
  /// @return VITURE_GLASSES_SUCCESS on success, VITURE_GLASSES_ERROR_INVALID_PARAM on failure
  int xr_device_provider_get_gl_pose_carina(
    XRDeviceProviderHandle handle,
    ffi.Pointer<ffi.Float> pose,
    double predict_time,
    ffi.Pointer<ffi.Int> pose_status,
  ) {
    return _xr_device_provider_get_gl_pose_carina(
      handle,
      pose,
      predict_time,
      pose_status,
    );
  }

  late final _xr_device_provider_get_gl_pose_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle,
            ffi.Pointer<ffi.Float>,
            ffi.Double,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('xr_device_provider_get_gl_pose_carina');
  late final _xr_device_provider_get_gl_pose_carina =
      _xr_device_provider_get_gl_pose_carinaPtr
          .asFunction<
            int Function(
              XRDeviceProviderHandle,
              ffi.Pointer<ffi.Float>,
              double,
              ffi.Pointer<ffi.Int>,
            )
          >();

  /// @brief Enable automatic exposure for the Carina camera.
  ///
  /// @param handle Handle to the XRDeviceProvider instance
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_auto_exposure_carina(
    XRDeviceProviderHandle handle,
  ) {
    return _xr_device_provider_set_auto_exposure_carina(handle);
  }

  late final _xr_device_provider_set_auto_exposure_carinaPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle)>>(
        'xr_device_provider_set_auto_exposure_carina',
      );
  late final _xr_device_provider_set_auto_exposure_carina =
      _xr_device_provider_set_auto_exposure_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle)>();

  /// @brief Set manual (fixed) exposure for the Carina camera.
  ///
  /// Disables automatic exposure and applies the given exposure time and gain.
  /// Out-of-range values are clamped to the accepted ranges.
  ///
  /// @param handle           Handle to the XRDeviceProvider instance
  /// @param exposure_time_ms Exposure time in milliseconds, range [0.01, 8.0].
  /// @param exposure_gain    Sensor gain, range [0, 15].
  /// @return VITURE_GLASSES_SUCCESS on success, error code on failure
  int xr_device_provider_set_manual_exposure_carina(
    XRDeviceProviderHandle handle,
    double exposure_time_ms,
    int exposure_gain,
  ) {
    return _xr_device_provider_set_manual_exposure_carina(
      handle,
      exposure_time_ms,
      exposure_gain,
    );
  }

  late final _xr_device_provider_set_manual_exposure_carinaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle, ffi.Float, ffi.Int)
        >
      >('xr_device_provider_set_manual_exposure_carina');
  late final _xr_device_provider_set_manual_exposure_carina =
      _xr_device_provider_set_manual_exposure_carinaPtr
          .asFunction<int Function(XRDeviceProviderHandle, double, int)>();

  /// @brief Retrieve the current electrochromic film mode.
  ///
  /// The electrochromic film controls the tint level of the glasses lenses.
  /// The voltage value interpretation differs between device generations:
  /// - Gen1 devices: Binary mode (0.0 = off, 1.0 = on)
  /// - Gen2 devices: Multi-level mode (0.0, 0.125, 0.25, ..., 0.875, 1.0)
  ///
  /// For device-specific value ranges, see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param voltage Output parameter to store the current voltage value (0.0 to 1.0).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or null voltage pointer
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_film_mode(
    XRDeviceProviderHandle$1 handle,
    ffi.Pointer<ffi.Float> voltage,
  ) {
    return _xr_device_provider_get_film_mode(handle, voltage);
  }

  late final _xr_device_provider_get_film_modePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Float>)
        >
      >('xr_device_provider_get_film_mode');
  late final _xr_device_provider_get_film_mode =
      _xr_device_provider_get_film_modePtr
          .asFunction<
            int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Float>)
          >();

  /// @brief Set the electrochromic film mode.
  ///
  /// The electrochromic film controls the tint level of the glasses lenses.
  /// The voltage parameter interpretation differs between device generations:
  /// - Gen1 devices: Any non-zero value enables the film
  /// - Gen2 devices: Voltage is mapped to discrete tint levels
  ///
  /// For device-specific value ranges, see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param voltage Voltage value in range [0.0, 1.0].
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or voltage out of range
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_film_mode(
    XRDeviceProviderHandle$1 handle,
    double voltage,
  ) {
    return _xr_device_provider_set_film_mode(handle, voltage);
  }

  late final _xr_device_provider_set_film_modePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle$1, ffi.Float)
        >
      >('xr_device_provider_set_film_mode');
  late final _xr_device_provider_set_film_mode =
      _xr_device_provider_set_film_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, double)>();

  /// @brief Retrieve the current screen duty cycle.
  ///
  /// Duty cycle controls display brightness by adjusting the percentage of time
  /// that pixels are active. Higher values result in brighter displays.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Duty cycle value in range [0, 100] on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_duty_cycle(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_get_duty_cycle(handle);
  }

  late final _xr_device_provider_get_duty_cyclePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_get_duty_cycle',
      );
  late final _xr_device_provider_get_duty_cycle =
      _xr_device_provider_get_duty_cyclePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the screen duty cycle.
  ///
  /// Duty cycle controls display brightness by adjusting the percentage of time
  /// that pixels are active. Higher values result in brighter displays.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param duty_cycle Duty cycle value in range [0, 100].
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or value out of range
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_duty_cycle(
    XRDeviceProviderHandle$1 handle,
    int duty_cycle,
  ) {
    return _xr_device_provider_set_duty_cycle(handle, duty_cycle);
  }

  late final _xr_device_provider_set_duty_cyclePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_duty_cycle');
  late final _xr_device_provider_set_duty_cycle =
      _xr_device_provider_set_duty_cyclePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current wear status (Gen2 devices only).
  ///
  /// Reports whether the glasses are currently being worn, based on the wear
  /// detection sensor. Wear status changes are also reported through the state
  /// callback with VITURE_CALLBACK_ID_WEAR_STATUS.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param wear_status Output parameter: 0 = not worn, 1 = worn.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or null wear_status pointer
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device is not a Gen2 device
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_wear_status(
    XRDeviceProviderHandle$1 handle,
    ffi.Pointer<ffi.Uint8> wear_status,
  ) {
    return _xr_device_provider_get_wear_status(handle, wear_status);
  }

  late final _xr_device_provider_get_wear_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Uint8>)
        >
      >('xr_device_provider_get_wear_status');
  late final _xr_device_provider_get_wear_status =
      _xr_device_provider_get_wear_statusPtr
          .asFunction<
            int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Uint8>)
          >();

  /// @brief Retrieve the current display mode.
  ///
  /// Display mode determines both the resolution and refresh rate of the device output.
  /// On devices with native DOF support (e.g., Viture Beast), use this interface when in bypass mode.
  /// See VITURE_DISPLAY_MODE_* constants for valid mode values.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Display mode value (see VITURE_DISPLAY_MODE_* constants) on success,
  /// or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   Gen2 device is in native mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_display_mode(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_get_display_mode(handle);
  }

  late final _xr_device_provider_get_display_modePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_get_display_mode',
      );
  late final _xr_device_provider_get_display_mode =
      _xr_device_provider_get_display_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the display mode.
  ///
  /// Display mode determines both the resolution and refresh rate of the device output.
  /// On devices with native DOF support (e.g., Viture Beast), use this interface when in bypass mode.
  /// See VITURE_DISPLAY_MODE_* constants for valid mode values.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param display_mode Display mode value (see VITURE_DISPLAY_MODE_* constants).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or invalid mode value
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   Gen2 device is in native mode, or mode value unsupported
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_display_mode(
    XRDeviceProviderHandle$1 handle,
    int display_mode,
  ) {
    return _xr_device_provider_set_display_mode(handle, display_mode);
  }

  late final _xr_device_provider_set_display_modePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_display_mode');
  late final _xr_device_provider_set_display_mode =
      _xr_device_provider_set_display_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Set the default display mode applied when the glasses power on.
  ///
  /// The configured mode is stored in the device and persists across power cycles.
  /// See VITURE_DISPLAY_MODE_* constants for valid mode values.
  ///
  /// Supported on Viture Luma / Luma Pro only. Other devices (including Luma Ultra)
  /// return VITURE_GLASSES_ERROR_NOT_SUPPORTED.
  ///
  /// @param handle       Valid XRDeviceProvider handle.
  /// @param display_mode Display mode value (see VITURE_DISPLAY_MODE_* constants).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or invalid mode value
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   not supported on this device
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_default_display_mode(
    XRDeviceProviderHandle$1 handle,
    int display_mode,
  ) {
    return _xr_device_provider_set_default_display_mode(handle, display_mode);
  }

  late final _xr_device_provider_set_default_display_modePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_default_display_mode');
  late final _xr_device_provider_set_default_display_mode =
      _xr_device_provider_set_default_display_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Enable or disable the physical 2D/3D display mode switch button on the glasses.
  ///
  /// When disabled, pressing the hardware button has no effect. The setting is
  /// not persistent and resets to enabled on the next power cycle.
  ///
  /// Supported on Viture Luma / Luma Pro only. Other devices (including Luma Ultra)
  /// return VITURE_GLASSES_ERROR_NOT_SUPPORTED.
  ///
  /// @param handle  Valid XRDeviceProvider handle.
  /// @param enabled 1 to enable the button, 0 to disable it.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or invalid enabled value
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   not supported on this device
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_display_mode_button_enabled(
    XRDeviceProviderHandle$1 handle,
    int enabled,
  ) {
    return _xr_device_provider_set_display_mode_button_enabled(handle, enabled);
  }

  late final _xr_device_provider_set_display_mode_button_enabledPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_display_mode_button_enabled');
  late final _xr_device_provider_set_display_mode_button_enabled =
      _xr_device_provider_set_display_mode_button_enabledPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Switch between 2D and 3D display modes (Gen1 and Gen2 bypass mode only).
  ///
  /// This is a convenience function that switches between:
  /// - 2D mode: 1920x1080 @ 60Hz
  /// - 3D mode: 3840x1080 @ 60Hz
  ///
  /// On devices with native DOF support (e.g., Viture Beast) in native mode, use xr_device_provider_native_switch_dimension()
  /// instead. Calling this function in such state returns VITURE_GLASSES_ERROR_NOT_SUPPORTED.
  ///
  /// @note If the device is already in the requested mode, the function returns
  /// successfully (0) without performing any action.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param is_3d 1 to switch to 3D mode, 0 to switch to 2D mode.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device is Gen2 (use native_switch_dimension instead)
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_switch_dimension(
    XRDeviceProviderHandle$1 handle,
    int is_3d,
  ) {
    return _xr_device_provider_switch_dimension(handle, is_3d);
  }

  late final _xr_device_provider_switch_dimensionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_switch_dimension');
  late final _xr_device_provider_switch_dimension =
      _xr_device_provider_switch_dimensionPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current screen brightness level.
  ///
  /// Brightness levels vary by device model. For device-specific value ranges,
  /// see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Brightness level on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DATA_PARSE      response length or format mismatch
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_brightness_level(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_get_brightness_level(handle);
  }

  late final _xr_device_provider_get_brightness_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_get_brightness_level',
      );
  late final _xr_device_provider_get_brightness_level =
      _xr_device_provider_get_brightness_levelPtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the screen brightness level.
  ///
  /// Brightness levels vary by device model. For device-specific value ranges,
  /// see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param level Brightness level to set (device-specific range).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or value out of range
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_brightness_level(
    XRDeviceProviderHandle$1 handle,
    int level,
  ) {
    return _xr_device_provider_set_brightness_level(handle, level);
  }

  late final _xr_device_provider_set_brightness_levelPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_brightness_level');
  late final _xr_device_provider_set_brightness_level =
      _xr_device_provider_set_brightness_levelPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current speaker volume level.
  ///
  /// Volume levels vary by device model. For device-specific value ranges,
  /// see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Volume level on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DATA_PARSE      response length or format mismatch
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_volume_level(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_get_volume_level(handle);
  }

  late final _xr_device_provider_get_volume_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_get_volume_level',
      );
  late final _xr_device_provider_get_volume_level =
      _xr_device_provider_get_volume_levelPtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the speaker volume level.
  ///
  /// Volume levels vary by device model. For device-specific value ranges,
  /// see @ref ValueRanges.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param level Volume level to set (device-specific range).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or value out of range
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_set_volume_level(
    XRDeviceProviderHandle$1 handle,
    int level,
  ) {
    return _xr_device_provider_set_volume_level(handle, level);
  }

  late final _xr_device_provider_set_volume_levelPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_set_volume_level');
  late final _xr_device_provider_set_volume_level =
      _xr_device_provider_set_volume_levelPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the glasses firmware version string.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param response Output buffer to store the version string. Must be pre-allocated.
  /// @param length Input/output parameter: on input, specifies the buffer size;
  /// on output, contains the actual length of the version string.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle, null response, or null length
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_glasses_version(
    XRDeviceProviderHandle$1 handle,
    ffi.Pointer<ffi.Char> response,
    ffi.Pointer<ffi.Int> length,
  ) {
    return _xr_device_provider_get_glasses_version(handle, response, length);
  }

  late final _xr_device_provider_get_glasses_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            XRDeviceProviderHandle$1,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('xr_device_provider_get_glasses_version');
  late final _xr_device_provider_get_glasses_version =
      _xr_device_provider_get_glasses_versionPtr
          .asFunction<
            int Function(
              XRDeviceProviderHandle$1,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int>,
            )
          >();

  /// @brief Retrieve the SHA-256 hash of the board serial number.
  ///
  /// The raw serial number is never exposed. The caller receives a 32-byte
  /// SHA-256 digest that uniquely identifies the device and can be used for
  /// device binding or license validation without leaking the actual SN.
  ///
  /// @param handle    Valid XRDeviceProvider handle.
  /// @param hash_out  Caller-allocated buffer of at least 32 bytes to receive the digest.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or null hash_out
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_get_sn_hash(
    XRDeviceProviderHandle$1 handle,
    ffi.Pointer<ffi.Uint8> hash_out,
  ) {
    return _xr_device_provider_get_sn_hash(handle, hash_out);
  }

  late final _xr_device_provider_get_sn_hashPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Uint8>)
        >
      >('xr_device_provider_get_sn_hash');
  late final _xr_device_provider_get_sn_hash =
      _xr_device_provider_get_sn_hashPtr
          .asFunction<
            int Function(XRDeviceProviderHandle$1, ffi.Pointer<ffi.Uint8>)
          >();

  /// @brief Retrieve the current mode for Gen2 devices (bypass / native).
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Returns whether the device is operating in bypass mode or native mode:
  /// - 0 (bypass mode): native DOF tracking is disabled; use xr_device_provider_get/set_display_mode
  /// for display mode control.
  /// - 1 (native mode): native DOF tracking is active; use xr_device_provider_native_get/set_display_mode
  /// for display mode control.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return 0 (bypass) or 1 (native) on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   feature not supported by device
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_mode(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_native_get_mode(handle);
  }

  late final _xr_device_provider_native_get_modePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_mode',
      );
  late final _xr_device_provider_native_get_mode =
      _xr_device_provider_native_get_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the native mode for Gen2 devices (bypass / native).
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// After calling this function, call xr_device_provider_native_set_display_mode() to complete
  /// the mode switch by setting an appropriate display mode for the new mode.
  /// Controls whether the device operates in bypass mode or native mode:
  /// - 0 (bypass mode): disables native DOF tracking; display mode is controlled via
  /// xr_device_provider_get/set_display_mode using standard VITURE_DISPLAY_MODE_* values.
  /// - 1 (native mode): enables native DOF tracking; display mode is controlled via
  /// xr_device_provider_native_get/set_display_mode using VITURE_NATIVE_DISPLAY_MODE_* values.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param mode 0 for bypass mode, 1 for native mode.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   feature not supported by device
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device rejected the command
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_mode(
    XRDeviceProviderHandle$1 handle,
    int mode,
  ) {
    return _xr_device_provider_native_set_mode(handle, mode);
  }

  late final _xr_device_provider_native_set_modePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_mode');
  late final _xr_device_provider_native_set_mode =
      _xr_device_provider_native_set_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current native DOF tracking type on Gen2 devices.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Returns the active DOF tracking type when the device is in native mode.
  /// See VITURE_NATIVE_DOF_* constants for valid values (e.g., VITURE_NATIVE_DOF_3,
  /// VITURE_NATIVE_DOF_SMOOTH_FOLLOW).
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return DOF tracking type (see VITURE_NATIVE_DOF_* constants) on success,
  /// or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_dof(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_native_get_dof(handle);
  }

  late final _xr_device_provider_native_get_dofPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_dof',
      );
  late final _xr_device_provider_native_get_dof =
      _xr_device_provider_native_get_dofPtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the native DOF tracking type on Gen2 devices.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Sets the active DOF tracking type when the device is in native mode.
  /// See VITURE_NATIVE_DOF_* constants for valid values (e.g., VITURE_NATIVE_DOF_3,
  /// VITURE_NATIVE_DOF_SMOOTH_FOLLOW).
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param dof DOF tracking type to set (see VITURE_NATIVE_DOF_* constants).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device rejected the command
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_dof(
    XRDeviceProviderHandle$1 handle,
    int dof,
  ) {
    return _xr_device_provider_native_set_dof(handle, dof);
  }

  late final _xr_device_provider_native_set_dofPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_dof');
  late final _xr_device_provider_native_set_dof =
      _xr_device_provider_native_set_dofPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Recenter the display for native DOF tracking.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// It resets the current head pose to the center position for DOF tracking when the device is in native mode.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_recenter_dof(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_native_recenter_dof(handle);
  }

  late final _xr_device_provider_native_recenter_dofPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_recenter_dof',
      );
  late final _xr_device_provider_native_recenter_dof =
      _xr_device_provider_native_recenter_dofPtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Retrieve the current display mode for Gen2 devices.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Use this when the device is operating in native DOF mode (not bypass).
  /// See VITURE_NATIVE_DISPLAY_MODE_* constants for valid mode values.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Display mode value (see VITURE_NATIVE_DISPLAY_MODE_* constants) on success,
  /// or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_display_mode(
    XRDeviceProviderHandle$1 handle,
  ) {
    return _xr_device_provider_native_get_display_mode(handle);
  }

  late final _xr_device_provider_native_get_display_modePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_display_mode',
      );
  late final _xr_device_provider_native_get_display_mode =
      _xr_device_provider_native_get_display_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the display mode for native DOF operation on Gen2 devices.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Use this when the device is operating in native DOF mode (not bypass).
  /// See VITURE_NATIVE_DISPLAY_MODE_* constants for valid mode values.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param display_mode Display mode value (see VITURE_NATIVE_DISPLAY_MODE_* constants).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or invalid mode value
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_display_mode(
    XRDeviceProviderHandle$1 handle,
    int display_mode,
  ) {
    return _xr_device_provider_native_set_display_mode(handle, display_mode);
  }

  late final _xr_device_provider_native_set_display_modePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_display_mode');
  late final _xr_device_provider_native_set_display_mode =
      _xr_device_provider_native_set_display_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current side mode for Gen2 devices in native mode.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast)
  /// and requires the device to be in native mode (mode == 1).
  /// Side mode shifts the displayed image to one side of the glasses.
  /// - 0: side mode disabled
  /// - 1: side mode enabled
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return 0 (disabled) or 1 (enabled) on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   feature not supported, or device is not in native mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_side_mode(XRDeviceProviderHandle$1 handle) {
    return _xr_device_provider_native_get_side_mode(handle);
  }

  late final _xr_device_provider_native_get_side_modePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_side_mode',
      );
  late final _xr_device_provider_native_get_side_mode =
      _xr_device_provider_native_get_side_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the side mode for Gen2 devices in native mode.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast)
  /// and requires the device to be in native mode (mode == 1).
  /// Side mode shifts the displayed image to one side of the glasses.
  /// - 0: disable side mode
  /// - 1: enable side mode
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param side_mode 0 to disable side mode, 1 to enable side mode.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   feature not supported, or device is not in native mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device rejected the command
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_side_mode(
    XRDeviceProviderHandle$1 handle,
    int side_mode,
  ) {
    return _xr_device_provider_native_set_side_mode(handle, side_mode);
  }

  late final _xr_device_provider_native_set_side_modePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_side_mode');
  late final _xr_device_provider_native_set_side_mode =
      _xr_device_provider_native_set_side_modePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Switch between 2D and 3D display modes in native DOF mode on Gen2 devices.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Switches between:
  /// - 2D mode: VITURE_NATIVE_DISPLAY_MODE_1920_1080_60HZ
  /// - 3D mode: VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1080_60HZ
  /// when the device is operating in native mode.
  ///
  /// @note If the device is already in the requested mode, the function returns
  /// successfully (0) without performing any action.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param is_3d 1 to switch to 3D mode, 0 to switch to 2D mode.
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_switch_dimension(
    XRDeviceProviderHandle$1 handle,
    int is_3d,
  ) {
    return _xr_device_provider_native_switch_dimension(handle, is_3d);
  }

  late final _xr_device_provider_native_switch_dimensionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_switch_dimension');
  late final _xr_device_provider_native_switch_dimension =
      _xr_device_provider_native_switch_dimensionPtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current display distance setting.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Display distance controls the virtual distance of the display content when the device is operating in native mode.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Display distance value in range [1, 10] on success, or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_display_distance(
    XRDeviceProviderHandle$1 handle,
  ) {
    return _xr_device_provider_native_get_display_distance(handle);
  }

  late final _xr_device_provider_native_get_display_distancePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_display_distance',
      );
  late final _xr_device_provider_native_get_display_distance =
      _xr_device_provider_native_get_display_distancePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the display distance.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Display distance controls the virtual distance of the display content when the device is operating in native mode.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param distance Display distance value in range [1, 10].
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or value out of range
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_display_distance(
    XRDeviceProviderHandle$1 handle,
    int distance,
  ) {
    return _xr_device_provider_native_set_display_distance(handle, distance);
  }

  late final _xr_device_provider_native_set_display_distancePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_display_distance');
  late final _xr_device_provider_native_set_display_distance =
      _xr_device_provider_native_set_display_distancePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();

  /// @brief Retrieve the current display size setting.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Display size controls the apparent size of the virtual display when the device is operating in native mode.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @return Display size value (see VITURE_DISPLAY_SIZE_* constants) in range [0, 4] on success,
  /// or a negative error code:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_DEVICE_REJECTED device returned error status
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_get_display_size(
    XRDeviceProviderHandle$1 handle,
  ) {
    return _xr_device_provider_native_get_display_size(handle);
  }

  late final _xr_device_provider_native_get_display_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1)>>(
        'xr_device_provider_native_get_display_size',
      );
  late final _xr_device_provider_native_get_display_size =
      _xr_device_provider_native_get_display_sizePtr
          .asFunction<int Function(XRDeviceProviderHandle$1)>();

  /// @brief Set the display size.
  ///
  /// This function is only available on devices with native DOF support (e.g., Viture Beast).
  /// Display size controls the apparent size of the virtual display when the device is operating in native mode.
  ///
  /// @param handle Valid XRDeviceProvider handle.
  /// @param size Display size value (see VITURE_DISPLAY_SIZE_* constants).
  /// @return VITURE_GLASSES_SUCCESS on success, or:
  /// - VITURE_GLASSES_ERROR_INVALID_PARAM   null handle or invalid size value
  /// - VITURE_GLASSES_ERROR_USB_UNAVAILABLE USB not available
  /// - VITURE_GLASSES_ERROR_NOT_SUPPORTED   device does not support native DOF, or device is in bypass mode
  /// - VITURE_GLASSES_ERROR_USB_EXEC        USB execution error
  /// - VITURE_GLASSES_ERROR_UNKNOWN         other error
  int xr_device_provider_native_set_display_size(
    XRDeviceProviderHandle$1 handle,
    int size,
  ) {
    return _xr_device_provider_native_set_display_size(handle, size);
  }

  late final _xr_device_provider_native_set_display_sizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(XRDeviceProviderHandle$1, ffi.Int)>
      >('xr_device_provider_native_set_display_size');
  late final _xr_device_provider_native_set_display_size =
      _xr_device_provider_native_set_display_sizePtr
          .asFunction<int Function(XRDeviceProviderHandle$1, int)>();
}

/// @brief Handle type for XRDeviceProvider instances. This is an opaque pointer
/// returned by `xr_device_provider_create` and consumed by other API calls.
typedef XRDeviceProviderHandle = ffi.Pointer<ffi.Void>;
typedef GlassStateCallbackFunction = ffi.Void Function(
  ffi.Int glass_state_id,
  ffi.Int glass_value,
);
typedef DartGlassStateCallbackFunction = void Function(
  int glass_state_id,
  int glass_value,
);

/// @brief Callback for reporting glass state changes (brightness, volume, display mode, etc.)
///
/// See `VITURE_CALLBACK_ID_*` constants in viture_protocol_public.h for detailed id and values
///
/// @param glass_state_id  Identifier for the state being reported.
/// @param glass_value     Integer value associated with the state.
typedef GlassStateCallback =
    ffi.Pointer<ffi.NativeFunction<GlassStateCallbackFunction>>;
typedef LogHookFunction = ffi.Void Function(
  ffi.Int level,
  ffi.Pointer<ffi.Char> tag,
  ffi.Pointer<ffi.Char> message,
);
typedef DartLogHookFunction = void Function(
  int level,
  ffi.Pointer<ffi.Char> tag,
  ffi.Pointer<ffi.Char> message,
);

/// @brief Log hook function type
///
/// This callback is invoked for each log message generated by the library.
/// It allows external applications to capture, filter, or redirect log messages
/// to custom logging systems (files, remote servers, crash reporting, etc.).
///
/// @param level Log level (0: None, 1: Error, 2: Info, 3: Debug)
/// @param tag Log tag (typically "libglasses")
/// @param message Log message content
typedef LogHook = ffi.Pointer<ffi.NativeFunction<LogHookFunction>>;
typedef VitureImuRawCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> data,
  ffi.Uint64 timestamp,
  ffi.Uint64 vsync,
);
typedef DartVitureImuRawCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> data,
  int timestamp,
  int vsync,
);

/// @brief Callback function type for imu raw data.
///
/// @param data      Pointer to raw data buffer (device-defined layout).
/// @param timestamp Timestamp in device timebase for IMU sample.
/// @param vsync     VSync timestamp associated with the sample.
///
/// Should be set before calling xr_device_provider_open_imu with VITURE_IMU_MODE_RAW
/// Data format:
/// 1. Viture One / Pro / Lite: [gyroscope_raw_x, gyroscope_raw_y, gyroscope_raw_z,
/// accelerometer_raw_x, accelerometer_raw_y, accelerometer_raw_z,
/// 0, 0, 0,
/// temperature]
/// 2. Viture Luma / Luma Pro / Beast / Pro 2: [gyroscope_raw_x, gyroscope_raw_y, gyroscope_raw_z,
/// accelerometer_raw_x, accelerometer_raw_y, accelerometer_raw_z,
/// magnetometer_raw_x, magnetometer_raw_y, magnetometer_raw_z,
/// temperature]
typedef VitureImuRawCallback =
    ffi.Pointer<ffi.NativeFunction<VitureImuRawCallbackFunction>>;
typedef VitureImuPoseCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> data,
  ffi.Uint64 timestamp,
);
typedef DartVitureImuPoseCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> data,
  int timestamp,
);

/// @brief Callback function type for imu pose data.
///
/// @param data      Pointer to pose data buffer
/// @param timestamp Timestamp in device timebase for IMU sample.
///
/// Should be set before calling xr_device_provider_open_imu with VITURE_IMU_MODE_POSE
/// Coordinate system: North-West-Up (NWU), X->North, Y->West, Z->Up.
/// Data format: [roll, pitch, yaw, quaternion_w, quaternion_x, quaternion_y, quaternion_z]
typedef VitureImuPoseCallback =
    ffi.Pointer<ffi.NativeFunction<VitureImuPoseCallbackFunction>>;
typedef XRPoseCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> pose,
  ffi.Double timestamp,
);
typedef DartXRPoseCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> pose,
  double timestamp,
);

/// @brief Callback invoked when a new pose sample is available, This function
/// returns pose data at the Camera's frequency (25 Hz). In most cases, this
/// interface can be ignored.
///
/// @param pose      Array of 7 floats: [px, py, pz, qw, qx, qy, qz].
/// @param timestamp Monotonic timestamp in seconds.
typedef XRPoseCallback =
    ffi.Pointer<ffi.NativeFunction<XRPoseCallbackFunction>>;
typedef XRVSyncCallbackFunction = ffi.Void Function(ffi.Double timestamp);
typedef DartXRVSyncCallbackFunction = void Function(double timestamp);

/// @brief VSync notification callback.
///
/// @param timestamp Monotonic timestamp in seconds when VSync occurred.
typedef XRVSyncCallback =
    ffi.Pointer<ffi.NativeFunction<XRVSyncCallbackFunction>>;
typedef XRImuCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Float> imu,
  ffi.Double timestamp,
);
typedef DartXRImuCallbackFunction = void Function(
  ffi.Pointer<ffi.Float> imu,
  double timestamp,
);

/// @brief IMU data callback for Carina device.
///
/// @param imu       IMU data: [ax, ay, az, gx, gy, gz].
/// @param timestamp Timestamp in seconds for the IMU sample.
typedef XRImuCallback = ffi.Pointer<ffi.NativeFunction<XRImuCallbackFunction>>;
typedef XRCameraCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Char> image_left0,
  ffi.Pointer<ffi.Char> image_right0,
  ffi.Pointer<ffi.Char> image_left1,
  ffi.Pointer<ffi.Char> image_right1,
  ffi.Double timestamp,
  ffi.Int width,
  ffi.Int height,
);
typedef DartXRCameraCallbackFunction = void Function(
  ffi.Pointer<ffi.Char> image_left0,
  ffi.Pointer<ffi.Char> image_right0,
  ffi.Pointer<ffi.Char> image_left1,
  ffi.Pointer<ffi.Char> image_right1,
  double timestamp,
  int width,
  int height,
);

/// @brief Camera frame callback for stereo frames.
///
/// @param image_left0   Pointer to left image buffer (frame 0).
/// @param image_right0  Pointer to right image buffer (frame 0).
/// @param image_left1   Pointer to left image buffer (frame 1).
/// @param image_right1  Pointer to right image buffer (frame 1).
/// @param timestamp     Frame timestamp.
/// @param width         Frame width in pixels.
/// @param height        Frame height in pixels.
typedef XRCameraCallback =
    ffi.Pointer<ffi.NativeFunction<XRCameraCallbackFunction>>;

/// @brief Opaque handle to an XRDeviceProvider instance.
///
/// This handle is used to identify and interact with a specific Viture glasses device.
/// It must be obtained through xr_device_provider_create() before use.
typedef XRDeviceProviderHandle$1 = ffi.Pointer<ffi.Void>;

const int VITURE_GLASSES_SUCCESS = 0;

const int VITURE_GLASSES_ERROR_INVALID_PARAM = -1;

const int VITURE_GLASSES_ERROR_USB_UNAVAILABLE = -2;

const int VITURE_GLASSES_ERROR_USB_EXEC = -3;

const int VITURE_GLASSES_ERROR_NOT_SUPPORTED = -4;

const int VITURE_GLASSES_ERROR_NO_DATA = -5;

const int VITURE_GLASSES_ERROR_DATA_PARSE = -6;

const int VITURE_GLASSES_ERROR_DEVICE_REJECTED = -7;

const int VITURE_GLASSES_ERROR_CALIB_INIT = -8;

const int VITURE_GLASSES_ERROR_SERIAL_FETCH = -9;

const int VITURE_GLASSES_ERROR_INVALID_STATE = -10;

const int VITURE_GLASSES_ERROR_UNKNOWN = -99;

const int LOG_LEVEL_NONE = 0;

const int LOG_LEVEL_ERROR = 1;

const int LOG_LEVEL_INFO = 2;

const int LOG_LEVEL_DEBUG = 3;

const int VITURE_VERSION_MAJOR = 2;

const int VITURE_VERSION_MINOR = 4;

const int VITURE_VERSION_PATCH = 0;

const String VITURE_VERSION_STRING = '2.4.0';

const String VITURE_MARKET_NAME_ONE = 'One';

const String VITURE_MARKET_NAME_PRO = 'Pro';

const String VITURE_MARKET_NAME_LITE = 'Lite';

const String VITURE_MARKET_NAME_LUMA = 'Luma';

const String VITURE_MARKET_NAME_LUMA_PRO = 'Luma Pro';

const String VITURE_MARKET_NAME_LUMA_ULTRA = 'Luma Ultra';

const String VITURE_MARKET_NAME_LUMA_CYBER = 'Luma Cyber';

const String VITURE_MARKET_NAME_BEAST = 'Beast';

const String VITURE_MARKET_NAME_PRO2 = 'Pro 2';

const int VITURE_DISPLAY_MODE_1920_1080_60HZ = 49;

const int VITURE_DISPLAY_MODE_3840_1080_60HZ = 50;

const int VITURE_DISPLAY_MODE_1920_1080_90HZ = 51;

const int VITURE_DISPLAY_MODE_1920_1080_120HZ = 52;

const int VITURE_DISPLAY_MODE_3840_1080_90HZ = 53;

const int VITURE_DISPLAY_MODE_1920_1200_60HZ = 65;

const int VITURE_DISPLAY_MODE_3840_1200_60HZ = 66;

const int VITURE_DISPLAY_MODE_1920_1200_90HZ = 67;

const int VITURE_DISPLAY_MODE_1920_1200_120HZ = 68;

const int VITURE_DISPLAY_MODE_3840_1200_90HZ = 69;

const int VITURE_DUTY_CYCLE_H = 98;

const int VITURE_DUTY_CYCLE_M = 42;

const int VITURE_DUTY_CYCLE_L = 30;

const int VITURE_DISPLAY_SIZE_SMALL = 0;

const int VITURE_DISPLAY_SIZE_MEDIUM = 1;

const int VITURE_DISPLAY_SIZE_LARGE = 2;

const int VITURE_DISPLAY_SIZE_EXTRA = 3;

const int VITURE_DISPLAY_SIZE_ULTRA = 4;

const int VITURE_NATIVE_DOF_0 = 0;

const int VITURE_NATIVE_DOF_3 = 1;

const int VITURE_NATIVE_DOF_SMOOTH_FOLLOW = 2;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1080_60HZ = 49;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1080_90HZ = 50;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1080_120HZ = 51;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1200_60HZ = 52;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1200_90HZ = 53;

const int VITURE_NATIVE_DISPLAY_MODE_1920_1200_120HZ = 54;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1080_60HZ = 55;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1080_90HZ = 56;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1080_120HZ = 57;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1200_60HZ = 58;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1200_90HZ = 59;

const int VITURE_NATIVE_DISPLAY_MODE_3D_SBS_3840_1200_120HZ = 60;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1080_60HZ = 61;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1080_90HZ = 62;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1080_120HZ = 63;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1200_60HZ = 64;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1200_90HZ = 65;

const int VITURE_NATIVE_DISPLAY_MODE_ULTRAWIDE_3840_1200_120HZ = 66;

const int VITURE_IMU_MODE_RAW = 0;

const int VITURE_IMU_MODE_POSE = 1;

const int VITURE_IMU_FREQUENCY_LOW = 0;

const int VITURE_IMU_FREQUENCY_MEDIUM_LOW = 1;

const int VITURE_IMU_FREQUENCY_MEDIUM = 2;

const int VITURE_IMU_FREQUENCY_MEDIUM_HIGH = 3;

const int VITURE_IMU_FREQUENCY_HIGH = 4;

const int VITURE_IMU_FREQUENCY_ULTRA_HIGH = 5;

const int VITURE_CALLBACK_ID_BRIGHTNESS = 0;

const int VITURE_CALLBACK_ID_VOLUME = 1;

const int VITURE_CALLBACK_ID_DISPLAY_MODE = 2;

const int VITURE_CALLBACK_ID_ELECTROCHROMIC_FILM = 3;

const int VITURE_CALLBACK_ID_NATIVE_DOF = 4;

const int VITURE_CALLBACK_ID_WEAR_STATUS = 5;
